server:
  port: 8989

HASOR_DATAQL_DATAWAY: true

HASOR_DATAQL_DATAWAY_ADMIN: true

HASOR_DATAQL_DATAWAY_API_URL: /api/

HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

HASOR_DATAQL_FX_PAGE_DIALECT: mysql


# db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ttshop?serverTimezone=UTC&useSSL=true
    username: ${mysql_uname}
    password: ${mysql_pwd}
    driver-class-name: com.mysql.jdbc.Driver
    # druid
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1


