server:
  port: 8989
# 启用 Dataway 功能（默认不启用）
HASOR_DATAQL_DATAWAY: true
# 开启 ui 管理功能（注意生产环境必须要设置为 false，否则会造成严重的生产安全事故）
HASOR_DATAQL_DATAWAY_ADMIN: true
# （可选）API工作路径
HASOR_DATAQL_DATAWAY_API_URL: /api/
# （可选）ui 的工作路径，只有开启 ui 管理功能后才有效
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

HASOR_DATAQL_FX_PAGE_DIALECT: mysql


# db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ttshop?serverTimezone=UTC&useSSL=true
    username: ${mysql_uname}
    password: ${mysql_pwd}
    driver-class-name: com.mysql.jdbc.Driver
    # druid
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1


